package captioners

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

// Gemini implements the Captioner interface using Google's Gemini API
type Gemini struct {
	apiKey  string
	client  *http.Client
	baseURL string
}

// NewGemini creates a new Gemini captioner
func NewGemini(apiKey string) *Gemini {
	return &Gemini{
		apiKey:  apiKey,
		client:  &http.Client{},
		baseURL: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-pro:generateContent",
	}
}

// CaptionSingle generates a caption for a single image
func (g *Gemini) CaptionSingle(imageBase64, systemPrompt string) (string, error) {
	if g.apiKey == "" {
		return "", ErrAPIKeyRequired
	}

	if systemPrompt == "" {
		systemPrompt = "Describe this image in detail for training a diffusion model. Focus on the visual elements, composition, style, and any notable features."
	}

	request := geminiRequest{
		Contents: []geminiContent{
			{
				Parts: []geminiPart{
					{Text: systemPrompt},
					{
						InlineData: &geminiInlineData{
							MimeType: detectMimeType(imageBase64),
							Data:     imageBase64,
						},
					},
				},
			},
		},
	}

	return g.makeRequest(request)
}

// CaptionEdit generates a caption describing the difference between two images
func (g *Gemini) CaptionEdit(imageABase64, imageBBase64, systemPrompt string) (string, error) {
	if g.apiKey == "" {
		return "", ErrAPIKeyRequired
	}

	if systemPrompt == "" {
		systemPrompt = "Compare these two images and describe the edit or transformation that was applied to convert the first image into the second image. Focus on the specific changes made, including any adjustments to color, lighting, objects, text, style, or composition. Be concise and descriptive."
	}

	request := geminiRequest{
		Contents: []geminiContent{
			{
				Parts: []geminiPart{
					{Text: systemPrompt},
					{
						InlineData: &geminiInlineData{
							MimeType: detectMimeType(imageABase64),
							Data:     imageABase64,
						},
					},
					{
						InlineData: &geminiInlineData{
							MimeType: detectMimeType(imageBBase64),
							Data:     imageBBase64,
						},
					},
				},
			},
		},
	}

	return g.makeRequest(request)
}

// makeRequest handles the HTTP request to Gemini API
func (g *Gemini) makeRequest(request geminiRequest) (string, error) {
	requestBody, err := json.Marshal(request)
	if err != nil {
		return "", fmt.Errorf("failed to marshal request: %v", err)
	}

	url := fmt.Sprintf("%s?key=%s", g.baseURL, g.apiKey)

	resp, err := g.client.Post(url, "application/json", bytes.NewBuffer(requestBody))
	if err != nil {
		return "", fmt.Errorf("failed to call Gemini API: %v", err)
	}
	defer resp.Body.Close()

	responseBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("failed to read response: %v", err)
	}

	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("Gemini API error (status %d): %s", resp.StatusCode, string(responseBody))
	}

	var geminiResponse geminiResponse
	if err := json.Unmarshal(responseBody, &geminiResponse); err != nil {
		return "", fmt.Errorf("failed to unmarshal response: %v", err)
	}

	if geminiResponse.Error != nil {
		return "", fmt.Errorf("Gemini API error: %s", geminiResponse.Error.Message)
	}

	if len(geminiResponse.Candidates) == 0 || len(geminiResponse.Candidates[0].Content.Parts) == 0 {
		return "", fmt.Errorf("no caption generated by Gemini API")
	}

	return geminiResponse.Candidates[0].Content.Parts[0].Text, nil
}

// detectMimeType detects MIME type from base64 data
func detectMimeType(base64Data string) string {
	if len(base64Data) > 4 {
		switch base64Data[:4] {
		case "iVBO":
			return "image/png"
		case "UklG":
			return "image/webp"
		}
	}
	return "image/jpeg"
}

// Gemini API types
type geminiRequest struct {
	Contents []geminiContent `json:"contents"`
}

type geminiContent struct {
	Parts []geminiPart `json:"parts"`
}

type geminiPart struct {
	Text       string            `json:"text,omitempty"`
	InlineData *geminiInlineData `json:"inlineData,omitempty"`
}

type geminiInlineData struct {
	MimeType string `json:"mimeType"`
	Data     string `json:"data"`
}

type geminiResponse struct {
	Candidates []geminiCandidate `json:"candidates"`
	Error      *geminiError      `json:"error,omitempty"`
}

type geminiCandidate struct {
	Content geminiContent `json:"content"`
}

type geminiError struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}
