version: "3"

dotenv: [".env"]

vars:
  BACKEND_DIR: backend
  WEB_DIR: frontend

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  dev:
    desc: Run the project in development mode
    cmds:
      - concurrently "cd frontend && pnpm run dev" "cd backend && go build . && ./main"
