package gemini

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"

	"main/pkg/captioner"
)

// ProviderGemini represents the Gemini provider
const ProviderGemini captioner.Provider = "gemini"

// ModelGeminiPro represents the Gemini 2.5 Pro model
const ModelGeminiPro captioner.Model = "gemini-2.5-pro"

// endpointGeminiPro represents the Gemini 2.5 Pro endpoint
var endpointGeminiPro = url.URL{
	Scheme: "https",
	Host:   "generativelanguage.googleapis.com",
	Path:   "/v1beta/models/gemini-2.5-pro:generateContent",
}

type HTTPClient interface {
	Post(url, contentType string, body io.Reader) (*http.Response, error)
}

// Gemini implements the Captioner interface using Google's Gemini API
type Gemini struct {
	apiKey   string
	client   HTTPClient
	endpoint url.URL
}

// TODO: take a http.Client as a parameter instead of an endpoint for easier testing
// NewGemini creates a new Gemini captioner
func NewGemini(apiKey string, model captioner.Model, client HTTPClient) (*Gemini, error) {
	var endpoint = url.URL{}

	switch model {
	case ModelGeminiPro:
		endpoint = endpointGeminiPro
	default:
		return nil, fmt.Errorf("unsupported model: %s", model)
	}

	if client == nil {
		client = &http.Client{}
	}

	return &Gemini{
		apiKey:   apiKey,
		client:   client,
		endpoint: endpoint,
	}, nil
}

// CaptionSingle generates a caption for a single image
func (g *Gemini) CaptionSingle(ctx context.Context, image captioner.Image, systemPrompt string) (string, error) {
	if g.apiKey == "" {
		return "", fmt.Errorf("API key is required")
	}

	if systemPrompt == "" {
		systemPrompt = "Describe this image in detail for training a diffusion model. Focus on the visual elements, composition, style, and any notable features."
	}

	request := geminiRequest{
		Contents: []geminiContent{
			{
				Parts: []geminiPart{
					{Text: systemPrompt},
					{
						InlineData: &geminiInlineData{
							MimeType: image.MimeType.String(),
							Data:     image.Base64(),
						},
					},
				},
			},
		},
	}

	return g.makeRequest(request)
}

// CaptionEdit generates a caption describing the difference between two images
func (g *Gemini) CaptionEdit(ctx context.Context, imgA, imgB captioner.Image, systemPrompt string) (string, error) {
	if systemPrompt == "" {
		systemPrompt = "Compare these two images and describe the edit or transformation that was applied to convert the first image into the second image. Focus on the specific changes made, including any adjustments to color, lighting, objects, text, style, or composition. Be concise and descriptive."
	}

	request := geminiRequest{
		Contents: []geminiContent{
			{
				Parts: []geminiPart{
					{Text: systemPrompt},
					{
						InlineData: &geminiInlineData{
							MimeType: imgA.MimeType.String(),
							Data:     imgA.Base64(),
						},
					},
					{
						InlineData: &geminiInlineData{
							MimeType: imgB.MimeType.String(),
							Data:     imgB.Base64(),
						},
					},
				},
			},
		},
	}

	return g.makeRequest(request)
}

// makeRequest handles the HTTP request to Gemini API
func (g *Gemini) makeRequest(request geminiRequest) (string, error) {
	requestBody, err := json.Marshal(request)
	if err != nil {
		return "", fmt.Errorf("failed to marshal request: %v", err)
	}

	url := fmt.Sprintf("%s?key=%s", g.endpoint.String(), g.apiKey)

	resp, err := g.client.Post(url, "application/json", bytes.NewBuffer(requestBody))
	if err != nil {
		return "", fmt.Errorf("failed to call Gemini API: %v", err)
	}
	defer resp.Body.Close()

	responseBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("failed to read response: %v", err)
	}

	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("Gemini API error (status %d): %s", resp.StatusCode, string(responseBody))
	}

	var geminiResponse geminiResponse
	if err := json.Unmarshal(responseBody, &geminiResponse); err != nil {
		return "", fmt.Errorf("failed to unmarshal response: %v", err)
	}

	if geminiResponse.Error != nil {
		return "", fmt.Errorf("Gemini API error: %s", geminiResponse.Error.Message)
	}

	if len(geminiResponse.Candidates) == 0 || len(geminiResponse.Candidates[0].Content.Parts) == 0 {
		return "", fmt.Errorf("no caption generated by Gemini API")
	}

	return geminiResponse.Candidates[0].Content.Parts[0].Text, nil
}
