// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type CaptionTasksExpanded struct {
	ID          string    `json:"id"`
	ProjectID   string    `json:"project_id"`
	Type        string    `json:"type"`
	Status      string    `json:"status"`
	Priority    int64     `json:"priority"`
	Prompt      *string   `json:"prompt"`
	ResultText  *string   `json:"result_text"`
	Error       *string   `json:"error"`
	ScheduledAt *string   `json:"scheduled_at"`
	StartedAt   *string   `json:"started_at"`
	FinishedAt  *string   `json:"finished_at"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	ImageID     string    `json:"image_id"`
}

type EditTasksExpanded struct {
	ID          string    `json:"id"`
	ProjectID   string    `json:"project_id"`
	Type        string    `json:"type"`
	Status      string    `json:"status"`
	Priority    int64     `json:"priority"`
	Prompt      *string   `json:"prompt"`
	ResultText  *string   `json:"result_text"`
	Error       *string   `json:"error"`
	ScheduledAt *string   `json:"scheduled_at"`
	StartedAt   *string   `json:"started_at"`
	FinishedAt  *string   `json:"finished_at"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	ImageAID    string    `json:"image_a_id"`
	ImageBID    string    `json:"image_b_id"`
}

type Image struct {
	ID            string    `json:"id"`
	ProjectID     string    `json:"project_id"`
	RelPath       string    `json:"rel_path"`
	FileHash      string    `json:"file_hash"`
	Phash         *string   `json:"phash"`
	Width         *int64    `json:"width"`
	Height        *int64    `json:"height"`
	FilesizeBytes *int64    `json:"filesize_bytes"`
	MetadataJson  *string   `json:"metadata_json"`
	Caption       *string   `json:"caption"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Project struct {
	ID                string    `json:"id"`
	Name              string    `json:"name"`
	Kind              string    `json:"kind"`
	ParentID          *string   `json:"parent_id"`
	CaptionProvider   *string   `json:"caption_provider"`
	SystemPrompt      *string   `json:"system_prompt"`
	AutoCaptionConfig *string   `json:"auto_caption_config"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type Task struct {
	ID          string    `json:"id"`
	ProjectID   string    `json:"project_id"`
	Type        string    `json:"type"`
	Status      string    `json:"status"`
	Priority    int64     `json:"priority"`
	Prompt      *string   `json:"prompt"`
	ResultText  *string   `json:"result_text"`
	Error       *string   `json:"error"`
	ScheduledAt *string   `json:"scheduled_at"`
	StartedAt   *string   `json:"started_at"`
	FinishedAt  *string   `json:"finished_at"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type TaskEvent struct {
	ID         int64     `json:"id"`
	TaskID     string    `json:"task_id"`
	PrevStatus *string   `json:"prev_status"`
	NewStatus  string    `json:"new_status"`
	Message    *string   `json:"message"`
	CreatedAt  time.Time `json:"created_at"`
}

type TaskImage struct {
	ID       int64  `json:"id"`
	TaskID   string `json:"task_id"`
	ImageID  string `json:"image_id"`
	Role     string `json:"role"`
	Position int64  `json:"position"`
}
