// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: projects.sql

package db

import (
	"context"
)

const GetProject = `-- name: GetProject :one
SELECT (
    id,
    name,
    kind,
    parent_id,
    caption_provider,
    system_prompt,
    auto_caption_config
) FROM projects WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id string) (interface{}, error) {
	row := q.queryRow(ctx, q.getProjectStmt, GetProject, id)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}
